insert into delivery_address (city, street, state, zip) values ('Bakersfield', '6 Columbus Plaza', 'CA', 93852);
insert into delivery_address (city, street, state, zip) values ('Wasco', '94 Tennyson Avenue', 'CA', 92372);
insert into delivery_address (city, street, state, zip) values ('Lamont', '44982 Valley Edge Street', 'CA', 93492);
insert into delivery_address (city, street, state, zip) values ('Wasco', '8 Shasta Drive', 'CA', 95189);
insert into delivery_address (city, street, state, zip) values ('Taft', '4 Schiller Drive', 'CA', 93003);
insert into delivery_address (city, street, state, zip) values ('Wasco', '8450 Sundown Drive', 'CA', 91361);
insert into delivery_address (city, street, state, zip) values ('Bakersfield', '2 Ridgeview Court', 'CA', 91716);
insert into delivery_address (city, street, state, zip) values ('Bakersfield', '01 Crowley Hill', 'CA', 94664);
insert into delivery_address (city, street, state, zip) values ('Bakersfield', '0411 Victoria Avenue', 'CA', 91046);
insert into delivery_address (city, street, state, zip) values ('Wasco', '8187 Jana Plaza', 'CA', 91311);
insert into delivery_address (city, street, state, zip) values ('Taft', '5 Muir Road', 'CA', 92005);
insert into delivery_address (city, street, state, zip) values ('Bakersfield', '2 Dakota Trail', 'CA', 95159);
insert into delivery_address (city, street, state, zip) values ('Bakersfield', '8288 Fordem Pass', 'CA', 93681);
insert into delivery_address (city, street, state, zip) values ('Wasco', '5980 Oak Valley Parkway', 'CA', 91415);
insert into delivery_address (city, street, state, zip) values ('Taft', '0 Arizona Hill', 'CA', 94345);
insert into delivery_address (city, street, state, zip) values ('Taft', '0740 Algoma Drive', 'CA', 93863);
insert into delivery_address (city, street, state, zip) values ('Arvin', '9041 Homewood Terrace', 'CA', 95049);
insert into delivery_address (city, street, state, zip) values ('Bakersfield', '684 Ilene Alley', 'CA', 95052);
insert into delivery_address (city, street, state, zip) values ('Lamont', '464 Sundown Plaza', 'CA', 95135);
insert into delivery_address (city, street, state, zip) values ('Taft', '46 Caliangt Way', 'CA', 93753);
insert into delivery_address (city, street, state, zip) values ('Lamont', '2473 Sachs Pass', 'CA', 94229);
insert into delivery_address (city, street, state, zip) values ('Arvin', '98 Moulton Crossing', 'CA', 92452);
insert into delivery_address (city, street, state, zip) values ('Arvin', '35507 Lakewood Lane', 'CA', 94511);
insert into delivery_address (city, street, state, zip) values ('Arvin', '4 Red Cloud Hill', 'CA', 94654);
insert into delivery_address (city, street, state, zip) values ('Taft', '7816 Eliot Drive', 'CA', 94064);