insert into order_status (status_id, status) values (1, 'new order');
insert into order_status (status_id, status) values (2, 'checked availability');
insert into order_status (status_id, status) values (3, 'credits checked');
insert into order_status (status_id, status) values (4, 'packed');
insert into order_status (status_id, status) values (5, 'out for delivery');
insert into order_status (status_id, status) values (6, 'delivered');
insert into order_status (status_id, status) values (7, 'delivery attempted - not received');
insert into order_status (status_id, status) values (8, 'contact customer');
insert into order_status (status_id, status) values (9, 'cancelled');
insert into order_status (status_id, status) values (-1, 'in store purchase');